<!DOCTYPE html>
<html lang="en"><head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title> | Glen Berseth</title>
    <link rel="canonical" href="/posts_drafts/2015-05-04-handling-segfaults-in-python-that-occur">
    

    <meta property="og:title" content="">
    <meta property="og:url" content="/posts_drafts/2015-05-04-handling-segfaults-in-python-that-occur">
    <meta property="og:site_name" content="Glen Berseth">
    <meta name="twitter:card" content="summary">
    <meta property="twitter:title" content="">

	<script type="text/javascript" id="MathJax-script" async
	  src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js">
	</script>
    <script type="application/ld+json">
    {"@type":"WebSite","headline":"Glen Berseth","url":"/","name":"Glen Berseth","@context":"https://schema.org"}</script>
    <!-- End Jekyll SEO tag -->

    <link rel="stylesheet" href="/assets/css/style.css">
    <!-- <link rel="stylesheet" href="/assets/main.css"> --></head>
<body><header class="site-header">

    <div class="wrapper"><a class="site-title" rel="author" href="/">Glen Berseth</a><nav class="site-nav">
            <input type="checkbox" id="nav-trigger" class="nav-trigger" />
            <label for="nav-trigger">
                <span class="menu-icon">
                    <svg viewBox="0 0 18 15" width="18px" height="15px">
                        <path d="M1.5 1.5 h15 M1.5 7.5 h15 M1.5 13.5 h15" stroke="black" stroke-width="3" stroke-linecap="round" />
                      </svg>
                </span>
            </label>

            <div class="trigger">
                    <a class="page-link" href="/">Home</a>
                
                    <a class="page-link" href="/people/">People</a>
                
                    <a class="page-link" href="/publications/">Publications</a>
                
                    <a class="page-link" href="/join/">Join Us</a>
                
                    <a class="page-link" href="/posts/">Posts</a>
                
                    <a class="page-link" href="/teaching/">Teaching</a>
                
                <a class="page-link" href="/fr/posts_drafts/2015-05-04-handling-segfaults-in-python-that-occur">Fr</a>
                
            </div>
        </nav></div>
    
</header>
<main class="page-content" aria-label="Content">
        <div class="wrapper">
            <article class="post h-entry" itemscope itemtype="http://schema.org/BlogPosting">

  <header class="post-header">
    <h1 class="post-title p-name" itemprop="name headline">Handling Segfaults in Python that occur in custom C++ libraries</h1>
    <p class="post-meta">
      <time class="dt-published" datetime="2015-05-04T03:03:00-04:00" itemprop="datePublished">May 4, 2015
      </time>• <span itemprop="author" itemscope itemtype="http://schema.org/Person"><span class="p-author h-card" itemprop="name">Glen Berseth</span></span></p>
  </header>

  <div class="post-content e-content" itemprop="articleBody">
    <p>I am using a rather large C++ library to run some simulations. I have wrapped a function that calls this library which results in a large amount of processing. Very rarely and somewhat randomly the C++ library will segfault. It is not the point to debug the library because this simulation process views a segmentation similar to a failed test cases and the libraries <i>scores</i><i> </i>will reflect this error. <br /><br />Instead what I want to do is gracefully handle this segfault. The default behaviour in python is for the process to hang. Python is calling a library that runs a bunch of processing and python will wait until this function returns or a exception is thrown. However in the case I describe neither of these events occur.<br /><br />Lets start with some basic C++ code:<br /><br />&lt;pre&gt;<code><br />extern "C" {<br /><br />&nbsp;&nbsp;&nbsp; int raise_a_fault(int r)<br />&nbsp;&nbsp;&nbsp; {<br />&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; std::cout &lt;&lt; "r is "&lt;&lt; r &lt;&lt; std::endl;<br />&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; if (r &gt; 3)<br />&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; {<br />&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; volatile int *p = reinterpret_cast<volatile int="">(0);<br />&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; *p = 0x1337D00D; // force a segfault<br />&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; // raise(SIGSEGV); // this was not effective enough<br />&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; }<br />&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; else<br />&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; {<br />&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; return r;<br />&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; }<br />&nbsp;&nbsp;&nbsp; }<br />}</volatile>&nbsp; </code>&lt;/pre&gt;<br />This C++ library function will force a segmentation fault if r is greater than 3.<br /><br />I am using the ctypes library from python to link to the C++ library<br /><br /><br />&lt;pre&gt;<code><br />from ctypes import cdll<br />lib = cdll.LoadLibrary('./libFoo.so')</code>&lt;/pre&gt;&lt;pre&gt;<code>from multiprocessing import Pool </code>&lt;/pre&gt;&lt;pre&gt;<code>&nbsp;</code>&lt;/pre&gt;&lt;pre&gt;<code>def raise_a_fault(dummy):<br />&nbsp;&nbsp;&nbsp; return lib.raise_a_fault(dummy)&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code>&lt;/pre&gt;&lt;pre&gt;<code>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</code>&lt;/pre&gt;&lt;pre&gt;<code>p = Pool(1)</code>&lt;/pre&gt;&lt;pre&gt;<code>items = [1, 2, 3, 4, 5]</code>&lt;/pre&gt;&lt;pre&gt;<code>results = p.map(raise_a_fault, items) </code>&lt;/pre&gt;&lt;pre&gt;<code><br />print results<br /></code>&lt;/pre&gt;<br />This script will terminate with “Segmentation fault (core dumped)”. raise_a_fault() will not return anything and the interpreter will exit. Now instead what if I want to run this over a number of processes to speed up processing time.<br /><br />&lt;pre&gt;<code><br /></code><code><code><br />from ctypes import cdll<br />lib = cdll.LoadLibrary('./libFoo.so')</code></code>&lt;/pre&gt;&lt;pre&gt;<code><code>from multiprocessing import Pool </code><code>&nbsp;</code></code>&lt;/pre&gt;&lt;pre&gt;<code><code>def raise_a_fault(dummy):<br />&nbsp;&nbsp;&nbsp; return lib.raise_a_fault(dummy)&nbsp;&nbsp;</code></code>&lt;/pre&gt;&lt;pre&gt;<code><code>&nbsp;</code></code>&lt;/pre&gt;&lt;pre&gt;<code><code></code><code>p = Pool(1)</code></code>&lt;/pre&gt;&lt;pre&gt;<code><code>items = [1, 2, 3, 4, 5, 4, 3, 2, 1, 10, 2]</code></code>&lt;/pre&gt;&lt;pre&gt;<code><code>results = p.map(raise_a_fault, items) </code><code></code><br />print results<br /></code>&lt;/pre&gt;<br />This will never terminate. The subprocess used in the pool with fault and exit without returning a value and the map function will wait, patiently, for a return value. For me I can’t even end the script with crtl+c. I have to use ctrl+z which ends up leaving a orphaned process behind.<br /><br />One supposed solution is to add a new signal handler to check for Segmentation fault signals<br /><br /><code><code>from ctypes import cdll lib = cdll.LoadLibrary('./libFoo.so')</code></code><br />&lt;pre&gt;<code><code>from multiprocessing import Pool </code><code>&nbsp;</code></code>&lt;/pre&gt;&lt;pre&gt;<code><code>def raise_a_fault(dummy):<br />&nbsp;&nbsp;&nbsp; return lib.raise_a_fault(dummy)&nbsp;&nbsp;</code></code>&lt;/pre&gt;&lt;pre&gt;<code><code>&nbsp;</code></code>&lt;/pre&gt;&lt;pre&gt;<code><code>def sig_handler(signum, frame):<br />    print "segfault"<br />    return None </code></code>&lt;/pre&gt;&lt;pre&gt;<code><code>signal.signal(signal.SIGSEGV, sig_handler)</code></code>&lt;/pre&gt;&lt;pre&gt;<code><code>&nbsp;</code></code>&lt;/pre&gt;&lt;pre&gt;<code><code></code><code>p = Pool(1)</code></code>&lt;/pre&gt;&lt;pre&gt;<code><code>items = [1, 2, 3, 4, 5, 4, 3, 2, 1, 10, 2]</code></code>&lt;/pre&gt;&lt;pre&gt;<code><code>results = p.map(raise_a_fault, items) </code><code></code><br />print results<br /></code>&lt;/pre&gt;<br /><br />This still has some odd issues. There seems to be some race condition that leads the processes to consume the resources of the processor but the processes do not advance. It might have something to do with this bug <a href="http://bugs.python.org/issue8296" target="_blank">bug</a>. Generally passing signals to child processes is tricky business in Python. Child processes will ignore <i>signals</i> when they are busy processing worker functions. I have seen suggestions to instead add a timeout on to the call to p.map().(timeout=1). This had no effect for me.<br /><br />A different solution that I have used before has more promise. This solution involves replacing map with apply_async(). In this case non of the signal handling is needed.<br /><br /><br /><br /><code><code>from ctypes import cdll lib = cdll.LoadLibrary('./libFoo.so')</code></code><br />&lt;pre&gt;<code><code>from multiprocessing import Pool </code><code>&nbsp;</code></code>&lt;/pre&gt;&lt;pre&gt;<code><code>&nbsp;</code></code>&lt;/pre&gt;&lt;pre&gt;<code><code>def print_results(result):<br />    print "callback result: ***************** " + str (result)<br />&nbsp;</code></code>&lt;/pre&gt;&lt;pre&gt;<code><code>def raise_a_fault(dummy):<br />    print "raise_a_fault, pid " + str(os.getpid())<br />    try:<br />        return lib.raise_a_fault(dummy)<br />    except Exception as inst:<br />        print "The fault is " + str(inst)<br />        # ctypes.set_errno(-2)</code></code>&lt;/pre&gt;&lt;pre&gt;<code><code>&nbsp;</code></code>&lt;/pre&gt;&lt;pre&gt;<code><code></code><code>processes_pool = Pool(2)<br />print "main, pid " + str(os.getpid())<br />items = [1, 2, 3, 4, 5, 4, 3, 2, 1, 10, 2]<br /><br />try:<br />    for item in items:<br /><br />        try:</code></code>&lt;/pre&gt;&lt;pre&gt;<code><code>            # this ensures the results come out in the same order the the experiemtns are in this list.<br />            result = processes_pool.apply_async(raise_a_fault, args = (item, ), callback = print_results)<br />            result.get(timeout=1)<br />        except Exception as inst:<br />            print "The exception is " + str(inst)<br />            continue<br />    processes_pool.join()<br />    <br />except Exception as inst:<br />    print "The Out exception is " + str(inst)</code></code>&lt;/pre&gt;&lt;pre&gt;<code><code> </code></code>&lt;/pre&gt;&lt;pre&gt;<code><code>print "All Done!" </code></code>&lt;/pre&gt;<br />The output:<br /><br /><br />main, pid 23466<br />raise_a_fault, pid 23467<br />r is 1<br />callback result: <strong>**</strong><strong>**</strong><strong>*** 1<br />raise_a_fault, pid 23468<br />r is 2<br />callback result: **</strong><strong>**</strong><strong>**</strong>* 2<br />raise_a_fault, pid 23467<br />r is 3<br />callback result: <strong>**</strong><strong>**</strong><strong>*** 3<br />raise_a_fault, pid 23468<br />r is 4<br />The exception is <br />raise_a_fault, pid 23467<br />r is 5<br />The exception is <br />raise_a_fault, pid 23475<br />r is 4<br />The exception is <br />raise_a_fault, pid 23479<br />r is 3<br />callback result: **</strong><strong>**</strong><strong>**</strong>* 3<br />raise_a_fault, pid 23483<br />r is 2<br />callback result: <strong>**</strong><strong>**</strong><strong>*** 2<br />raise_a_fault, pid 23479<br />r is 1<br />callback result: **</strong><strong>**</strong><strong>**</strong>* 1<br />raise_a_fault, pid 23483<br />r is 10<br />The exception is <br />raise_a_fault, pid 23479<br />r is 2<br />callback result: <strong>**</strong><strong>**</strong>***** 2<br />The Out exception is <br />All Done!<br /><br /><br /><br />This method is almost great. We have the output we want but we have to use a timeout. Some, including myself, don’t want to have to specify a definitive timeout where we expect the processing to be complete. It is not easy to find a nice solution to this problem, there are some <a href="https://bugs.python.org/issue3999" target="_blank">bugs</a> that make catching segfaults difficult.<br /><br />Unfortunately, this story has a tragic end. There does not seem to be good support for trapping SIGSEGV or many other signals in Python. I also tried some options in the C++ code. You can change how signals are handled in the C++ code but all that can effectively be done is to raise another signal. Useful exceptions can not be throw from a signal handler because they are essentially on a different stack frame. The solution presented seems to work the best. It does have the added benefit that processes do not <i>crash</i>. By not crashing I am referring to having the process exit() resulting in the process pool reduce the number of processes in the pool which could eventually lead to no processes available.<br /><br />The code I used to play around with possible solutions can be found <a href="https://github.com/Neo-X/PythonCppWrapping" target="_blank">here</a>.<br /><br />References:<br />&lt;ol&gt;&lt;li&gt;https://docs.python.org/3/library/ctypes.html&lt;/li&gt;&lt;li&gt;http://stackoverflow.com/questions/1717991/throwing-an-exception-from-within-a-signal-handler &lt;/li&gt;&lt;/ol&gt;</p>

  </div><a class="u-url" href="/posts_drafts/2015-05-04-handling-segfaults-in-python-that-occur" hidden></a>
</article>

        </div>
    </main><footer class="site-footer h-card">
    <data class="u-url" href="/%20/"></data>

    <div class="wrapper">
        

        <div class="footer-col-wrapper">
            <div class="footer-col footer-col-1">
                <ul class="contact-list">
                    <li class="p-name">Glen Berseth</li></ul>
            </div>

            <div class="footer-col footer-col-2"><ul class="social-media-list"><li><a href="https://github.com/neo-x"><svg
                class="svg-icon">
                <use xlink:href="/assets/minima-social-icons.svg#github"></use>
            </svg> <span class="username">neo-x</span></a></li><li><a
            href="https://www.linkedin.com/in/glen-berseth-0523278b"><svg class="svg-icon">
                <use xlink:href="/assets/minima-social-icons.svg#linkedin"></use>
            </svg> <span class="username">glen-berseth-0523278b</span></a></li><li><a
            href="https://www.twitter.com/GlenBerseth"><svg class="svg-icon">
                <use xlink:href="/assets/minima-social-icons.svg#twitter"></use>
            </svg> <span class="username">GlenBerseth</span></a></li><li><a rel="me"
            href="https://www.youtube.com/channel/UCOouaBg4gHIlNvPkJn_8ooA"
            title="Real Lab"><svg class="svg-icon grey">
                <use xlink:href="/assets/minima-social-icons.svg#youtube"></use>
            </svg> <span class="username">Real Lab</span></a></li></ul></div>

            <div class="footer-col footer-col-3">
                <p>I (he/him/il) am an assistant professor at the University de Montreal and Mila. My research explores how to use deep learning and reinforcement learning to develop generalist robots.</p>
            </div>
        </div>

    </div>

</footer></body>

</html>